v2.0.0
wdhdev/EasyScript pull request #45
Opened 2023-01-16 14:09 UTC by avalynndev

a release that updates the code from JavaScript to typescript.

# Requirements

- [x] The base branch is pointing to the correct branch. 

## Codebase

- [x] This code has been tested with the [latest release](https://github.com/EasyScriptJS/EasyScript/releases/latest) of Easy Script.
- [x] This code works with the [latest release](https://github.com/EasyScriptJS/EasyScript/releases/latest) of Easy Script.
- [x] This code has been run through [Prettier](https://prettier.io).

### Modules

- [x] I have provided documentation of how this code works. 

# Description

Converts the code from JavaScript to typescript. Adds new features, making it more usefull

2023-01-16 22:43 UTC, WilliamDavidHarrison requested changes
Can you please run the code through prettier replacing semi colons with regular colons.

aka ' -> "

2023-01-17 10:56 UTC, avalynndev commented
I don't understand what you mean. Please send an example.

2023-01-17 11:41 UTC, wdhdev requested changes
Please also move modules back into `/modules` folder

2023-01-17 11:41 UTC, wdhdev commented on index.ts
> +/** Others **/
```suggestion
/** Util **/
```

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on index.ts
> +/** Converting Modules **/
Please move this section into util section as these are no longer located in the types module

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/flip.ts
> +/**
This file has been updated since

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/log.ts
> +/**
This file has been updated since

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/print.ts
> + * @function `print` - Quickly log any data to the console.
This file has been updated since

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/random.ts
> +/**
This file has been updated since

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/types/boolToNum.ts
> +export function boolToNum(boolean: boolean): number {
This file has been updated since to include self docs.

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/types/numToBool.ts
> +export function numToBool(number: number): boolean {
This file has been updated since to include self docs.

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/types/numToStr.ts
> +export function numToStr(number: number): string {
This file has been updated since to include self docs.

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/types/strToBool.ts
> +export function strToBool(string: string): boolean {
This file has been updated since to include self docs.

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/types/strToNum.ts
> +export function strToNum(string: string): number {
This file has been updated since to include self docs.

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/util/removeDuplicates.ts
> +import { ObjectType } from "typescript";
This file has been updated since

2023-01-17 11:41 UTC, WilliamDavidHarrison commented on src/uuid.ts
> +/**
This file has been updated since

2023-01-18 11:01 UTC, merged